### ISSUE TITLE
Fine-tune the login page styles

### ISSUE THREAD

**Issue by mikestone14** [kolide/fleet#153]
### TODO:
- [ ] Footer is not a "sticky" footer. As I shrink the page the footer should know when to stop so it doesn't collide and overlap with the main-div but stay stuck to the bottom when there is ample room.
- [ ] Background div needs to have a 0.4 opacity to match the mocks.
- [ ] Gradient on the button has the wrong direction should be

```
/* Button Styling: */
backgroundImage: 'linear-gradient(-134deg, #7166D9 0%, #C86DD7 100%)',
```
- [ ] On load I would like to see the cursor automatically inserted into the username and password field
- [ ] Login div becomes uncentered vertically as you shrink the page
- [ ] Page needs minimum width applied so that you can't shrink it smaller than the width of the login div.
- [ ] Change font family
