### ISSUE TITLE
All Hosts - /hosts/all

### ISSUE THREAD

**Issue by terracatta** [kolide/fleet#367]
## Mock
[Zeplin - All Hosts](https://app.zeplin.io/project.html#pid=57e17b71c5b31ff827f26ba6&dashboard&tags=all-hosts)

![hosts-all-hosts-label-inspector-host-modal 2x](https://cloud.githubusercontent.com/assets/931724/19903838/7704921e-a046-11e6-8f1e-5e217bb54cab.png)
![hosts-all-hosts-label-list 2x](https://cloud.githubusercontent.com/assets/931724/19903839/7705394e-a046-11e6-9055-b8b02be483ff.png)
![hosts-all-hosts-label-grid 2x](https://cloud.githubusercontent.com/assets/931724/19903837/770167a6-a046-11e6-88a9-c175bda89300.png)

## Story
As a user I need the ability to see all the hosts monitored by Kolide in my infrastructure. To stay organized as I add more devices, I need to keep them labeled and those labels populated with dynamic queries.

### Platform / Status Labels Hardcoded
While you can make your own labels (or delete them). The status label options and the platform options in the sidebar cannot 

### Deleting Labels
Labels can be used as valid targets to packs. When a label with dependencies is deleted, those targets will automatically removed from those dependencies. There is no undo for this, so a user should confirm and make sure they really want to delete a label and the confirmation dialog should include the dependencies so the user is aware of them.

### Immutable Queries in Labels
While you can change the name of the label you cannot change the SQL of a query of a label that is already populated.

### Pre-populated Labels
When the product ships it will ship with pre-populated labels useful for common categorization. (We will determine these labels at a later date). User can use or delete these labels as they see fit.

### Related Issues

*  New Label - 380 

##  Engineering Tasks
- [x] Include the number of hosts in labels in label APIs (#404) (1 day)
- [x] Add label queries for all host card attributes (#405) (3 days)
- [x] Account for host status "MIA" (#406) (1 day)
- [x] Add built-in labels for operating systems (#407) (2 days)
