### ISSUE TITLE
Add Hosts - /hosts/new

### ISSUE THREAD

**Issue by FritzX6** [kolide/fleet#379]
## Note

This page doesn't look like this anymore. If you need the latest, talk to @marpaia.

## Original Mock

[Zeplin - Add Hosts](https://app.zeplin.io/project.html#pid=57e17b71c5b31ff827f26ba6&dashboard&tags=add-hosts)
![hosts-add-hosts 2x](https://cloud.githubusercontent.com/assets/931724/19903288/82f4a9e4-a044-11e6-904b-1012f4e16d86.png)

## Story
As a user I need the ability to easily and conveniently add hosts to my Kolide fleet preferably using IT automation tools I already have in place.

### Script Requirements
Ideally the one-liner script would do the following:

* Show a pretty welcome message
* Peform OS detection and download the correct osqueryd client
* Prompt the user to resolve (or self-resolve) any dependencies needed for osquery to function correctly (certs/certificate chains, etc.)
* Correctly advise the user on various edge cases (duplicate osqueryd client etc)
* Bootstrap osqueryd with a config file needed to contact Kolide
* Setup osqueryd process to survive restarts
* Start the osqueryd process and provide a success message with any additional information
* Output all pertinent data a log for later troubleshooting

### Need More Methods Explained
These methods will link to a Github repo or help documentation containing the relevant instructions needed for the additional method to work.

### Recently Added
The recently added panel provides a user with visual confirmation that new host has been added.

##  Engineering Tasks
- [ ] ~~Recently Added Hosts API Endpoint (#397) (1 day)~~
- [ ] ~~Infrastructure: osquery-kolide chef cookbook (#398) (3 days)~~
- [ ]  ~~Infrastructure: osquery-kolide ansible playbook (#399) (3 days)~~
- [ ] ~~Infrastructure: osquery-kolide puppet module (#400) (3 days)~~
- [ ] ~~Infrastructure: Install Tool (#401) (3 days)~~
- [ ] ~~Endpoint which serves install tool (#402) (1 day)~~
