### ISSUE TITLE
Connect user registration to the API

### ISSUE THREAD

**Issue by mikestone14** [kolide/fleet#486]
Related to #378 

**TODO:**
- [ ] Handle config based on `require-setup` key
- [ ] Submit form to setup endpoint
- [ ] Handle API response
